M48
; DRILL file {KiCad 9.0.6} date 2025-12-07T09:04:40+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T09:04:40+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X131.4Y-92.25
X136.0Y-92.25
X136.0Y-92.25
T2
X127.5Y-82.5
X127.5Y-97.5
X172.5Y-82.5
X172.5Y-97.5
M30
