M48
; DRILL file {KiCad 9.0.6} date 2025-12-07T09:03:42+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T09:03:42+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.400
%
G90
G05
T1
X169.75Y-93.35
T2
X127.5Y-82.5
X127.5Y-97.5
X172.5Y-82.5
X172.5Y-97.5
T3
X149.5Y-91.75
X161.5Y-91.75
M30
